const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const GET_LISTINGS = "GET_LISTINGS"
const GET_AMENITIES = "GET_AMENITIES"
const ADD_LISTING = "ADD_LISTING"
const UPDATE_LISTING = "UPDATE_LISTING"
const DELETE_LISTING = "DELETE_LISTING"
const GET_RESERVATIONS = "GET_RESERVATIONS"
const ADD_RESERVATION = "ADD_RESERVATION"

export { SET_CURRENT_USER, CLEAR_CURRENT_USER, GET_LISTINGS, GET_AMENITIES, ADD_LISTING , UPDATE_LISTING, DELETE_LISTING, GET_RESERVATIONS, ADD_RESERVATION}