const SET_CURRENT_USER = "SET_CURRENT_USER"
const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER"
const GET_LISTINGS = "GET_LISTINGS"
const GET_AMENITIES = "GET_AMENITIES"

export { SET_CURRENT_USER, CLEAR_CURRENT_USER, GET_LISTINGS, GET_AMENITIES }